### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by SkrytnayaRediska** [ZenyaBelkov/Homework_lesson_13#1]
https://github.com/ZenyaBelkov/Homework_lesson_13/blob/65c22e6ffcd83695fbfc4517ea4ed52f0b83f3c9/Homework13.py#L12

The generator stores the last state, so you don't have to use three variables and complicated logic with elifs. It is better to come up with a more general and optimal algorithm

**Comment by ZenyaBelkov** [comment]
Fixed in a new brunch
